---
name: .NET CI

on:
  pull_request:

concurrency:
  # Cancel any CI/CD workflow currently in progress for the same PR.
  # Allow running concurrently with any other commits.
  group: build-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_windows:
    permissions:
      actions: write  # for fkirc/skip-duplicate-actions to skip or stop workflow runs
      contents: read  # for actions/checkout to fetch code
    strategy:
      matrix:
        configurations: [Debug, Release]
    runs-on: windows-latest
    env:
      # Configuration type to build.  For documentation on how build matrices work, see
      # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
      BUILD_CONFIGURATION: ${{matrix.configurations}}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1  # v2.21.1
        with:
          egress-policy: audit

      - id: skip_check
        uses: fkirc/skip-duplicate-actions@b974a9395958c231af965b70070979a577efa578  # v5.3.2
        with:
          cancel_others: 'false'
          paths_ignore: '["**.md"]'

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        if: steps.skip_check.outputs.should_skip != 'true'
        with:
          submodules: 'recursive'

      - name: Build
        if: steps.skip_check.outputs.should_skip != 'true'
        run: |
          dotnet build OrcanodeMonitor.sln /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform="Any CPU"

      - name: Test
        if: steps.skip_check.outputs.should_skip != 'true'
        env:
          AZURE_COSMOS_CONNECTIONSTRING: ${{secrets.AZURE_COSMOS_CONNECTIONSTRING}}
          AZURE_COSMOS_DATABASENAME: ${{secrets.AZURE_COSMOS_DATABASENAME}}
          DATAPLICITY_API_KEY: ${{secrets.DATAPLICITY_API_KEY}}
          DATAPLICITY_ORG_HASH: ${{secrets.DATAPLICITY_ORG_HASH}}
          KUBERNETES_CA_CERT: ${{secrets.KUBERNETES_CA_CERT}}
          KUBERNETES_SERVICE_HOST: ${{secrets.KUBERNETES_SERVICE_HOST}}
          KUBERNETES_TOKEN: ${{secrets.KUBERNETES_TOKEN}}
        run: |
          dotnet test --no-build --verbosity normal --configuration ${{env.BUILD_CONFIGURATION}} --property:Platform="Any CPU"
